---
# Source: java-app-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: java-app-lb
  labels:
    helm.sh/chart: java-app-chart-0.1.0
    app.kubernetes.io/name: java-app-chart
    app.kubernetes.io/instance: app
    app.kubernetes.io/version: "1.30.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app: http-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
# Source: java-app-chart/templates/deployment.yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: java-app
  labels:
    helm.sh/chart: java-app-chart-0.1.0
    app.kubernetes.io/name: java-app-chart
    app.kubernetes.io/instance: app
    app.kubernetes.io/version: "1.30.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: java-app-chart
      app.kubernetes.io/instance: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: java-app-chart
        app.kubernetes.io/instance: app
    spec:
      containers:
        - name: java-app
          image: "mrtanko/jenkins-java-api:0.1"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /api/main
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/main
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          limits:
            cpu: "0.2"
            memory: 200Mi
          requests:
            cpu: "0.1"
            memory: 200Mi
